@url=http://localhost:4000

###GET
GET {{url}}/medicos

###POST
POST {{url}}/medicos
Content-Type: application/json

{
    "nombre": "pepe12",
    "apellido": "hola1234",
    "especialidad": "clinico",
    "matricula": "123456789"
}