@url=http://localhost:4000

### Login
# @name login
POST {{url}}/auth/login
Content-Type: application/json

{
    "nombre": "Celeste",
    "password": "Celes123"
}

###
@token = {{login.response.body.token}}

### Consultar usuarios
GET {{url}}/usuarios
Authorization: Bearer {{token}}

### Consultar por un usuario
GET {{url}}/usuarios/1


### Crear usuario
POST {{url}}/usuarios
Content-Type: application/json

{
    "nombre":"Celeste",
    "email": "cele.antenao@gmail.com",
    "password": "Celes123"
}

### Eliminar usuario 
DELETE {{url}}/usuarios/1
Authorization: Bearer {{token}}

### Modificar usuario 
PUT {{url}}/usuarios/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nombre":"Celeste",
    "email": "celee.antenao@gmail.com",
    "password": "Celes123"
}


