@url=http://localhost:4000

###GET
GET {{url}}/medicos


###GET
GET {{url}}/medicos/2

###POST
POST {{url}}/medicos
Content-Type: application/json

{
    "nombre": "Hola",
    "apellido": "chau",
    "especialidad": "Cirujana",
    "matricula": "a134a2asdsadsadsadsads234a"
}

###PUT
PUT {{url}}/medicos/6
Content-Type: application/json

{
    "nombre": "Fernanda",
    "apellido": "Antenao",
    "especialidad": "Cirujana",
    "matricula": "a134a2as234sd5a"
}

###PUT
DELETE {{url}}/medicos/7
