@url=http://localhost:4000

###GET
GET {{url}}/pacientes


###GET
GET {{url}}/pacientes/1

###POST
POST {{url}}/pacientes
Content-Type: application/json

{
    "nombre": "Fernanda",
    "apellido": "Antenao",
    "DNI": "45404258",
    "nacimiento": "2004-01-31",
    "obraSocial": "APOS"
}

###PUT
PUT {{url}}/pacientes/1
Content-Type: application/json

{
    "nombre": "Cele",
    "apellido": "Antenao",
    "DNI": "45470348",
    "nacimiento": "2004-01-13",
    "obraSocial": "APOS"
}

###PUT
DELETE {{url}}/pacientes/2
