@url=http://localhost:4000

### Variables
@url = http://localhost:4000


### Login
# @name login
POST {{url}}/auth/login
Content-Type: application/json

{
    "nombre": "Celeste",
    "password": "Celes123"
}

###
@token = {{login.response.body.token}}


###GET
GET {{url}}/pacientes
Authorization: Bearer {{token}}


###GET
GET {{url}}/pacientes/6
Authorization: Bearer {{token}}

###POST
POST {{url}}/pacientes
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nombre": "Fernanda",
    "apellido": "Antenao",
    "DNI": "45404258",
    "nacimiento": "2004-01-31",
    "obraSocial": "APOS"
}

###PUT
PUT {{url}}/pacientes/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nombre": "Cele",
    "apellido": "Antenao",
    "DNI": "45470348",
    "nacimiento": "2004-01-13",
    "obraSocial": "APOS"
}

###PUT
DELETE {{url}}/pacientes/6
Authorization: Bearer {{token}}
